language: perl
jobs:
  include:
    - perl: 5.8.1
      env:
        - AUTHOR_TESTING=0
        - HARNESS_VERBOSE=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
script:
  - perl -Ilib t/clean.t
branches:
  except:
    - /^wip\//
    - /^blocked/
notifications:
  email: false
  irc:
    channels:
      - "irc.perl.org#moo-smoke"
    template:
      - "%{repository}#%{build_number} %{branch} by %{author}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
    skip_join: true
